[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
test = "test"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = false

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=node_modules/forge-std/",
]

[fuzz]
runs = 1000
max_test_rejects = 100000

[invariant]
runs = 256
depth = 128
