export interface TemplateConfig {
  id: string
  name: string
  description: string
  repoTemplate: string
  stack: string[]
  cursorrules: string
  envExample: string
  githubActionsWorkflow: string
}

export const TEMPLATE_CONFIGS: Record<string, TemplateConfig> = {
  SERVERLESS_SAAS: {
    id: 'SERVERLESS_SAAS',
    name: 'Serverless SaaS',
    description: 'Next.js + Prisma + Supabase + Stripe + Auth on Vercel',
    repoTemplate: 'mismo-template-serverless-saas',
    stack: ['Next.js', 'Prisma', 'Supabase', 'Stripe', 'Vercel'],
    cursorrules: [
      'Never hardcode secrets or API keys',
      'Use environment variables for all configuration',
      'All database queries must use Prisma client',
      'Implement proper error handling with try/catch',
      'Use TypeScript strict mode',
      'No console.log in production code',
      'All API routes must validate input with Zod',
      'Use server components by default, client components only when needed',
      'Forbidden: eval(), Function(), innerHTML assignment',
      'Forbidden: SELECT * queries - always specify columns',
      'Forbidden: Storing plaintext passwords',
      'Run prisma generate after schema changes',
    ].join('\n'),
    envExample: [
      '# Database',
      'DATABASE_URL="postgresql://user:password@localhost:5432/mydb"',
      'DIRECT_URL="postgresql://user:password@localhost:5432/mydb"',
      '',
      '# Supabase',
      'NEXT_PUBLIC_SUPABASE_URL="https://your-project.supabase.co"',
      'NEXT_PUBLIC_SUPABASE_ANON_KEY="your-anon-key"',
      'SUPABASE_SERVICE_ROLE_KEY="your-service-role-key"',
      '',
      '# Stripe',
      'STRIPE_SECRET_KEY="sk_test_..."',
      'STRIPE_WEBHOOK_SECRET="whsec_..."',
      'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="pk_test_..."',
      '',
      '# Auth',
      'NEXTAUTH_SECRET="generate-a-random-secret"',
      'NEXTAUTH_URL="http://localhost:3000"',
      '',
      '# App',
      'NEXT_PUBLIC_APP_URL="http://localhost:3000"',
    ].join('\n'),
    githubActionsWorkflow: [
      'name: CI',
      'on:',
      '  push:',
      '    branches: [main]',
      '  pull_request:',
      '    branches: [main]',
      '',
      'jobs:',
      '  ci:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - uses: actions/setup-node@v4',
      '        with:',
      '          node-version: 20',
      '          cache: pnpm',
      '      - run: corepack enable',
      '      - run: pnpm install --frozen-lockfile',
      '      - run: pnpm type-check',
      '      - run: pnpm lint',
      '      - run: pnpm build',
      '      - run: pnpm test',
    ].join('\n'),
  },
  MONOLITHIC_MVP: {
    id: 'MONOLITHIC_MVP',
    name: 'Monolithic MVP',
    description: 'Next.js + SQLite + simple auth on Vercel',
    repoTemplate: 'mismo-template-monolithic-mvp',
    stack: ['Next.js', 'SQLite', 'Auth.js', 'Vercel'],
    cursorrules: [
      'Never hardcode secrets or API keys',
      'Use environment variables for all configuration',
      'Keep it simple - avoid premature optimization',
      'Implement proper error handling',
      'Use TypeScript strict mode',
      'No console.log in production code',
      'Forbidden: eval(), Function(), innerHTML assignment',
      'Forbidden: Storing plaintext passwords',
      'Use parameterized queries - never concatenate SQL strings',
    ].join('\n'),
    envExample: [
      '# Database',
      'DATABASE_URL="file:./dev.db"',
      '',
      '# Auth',
      'NEXTAUTH_SECRET="generate-a-random-secret"',
      'NEXTAUTH_URL="http://localhost:3000"',
      '',
      '# App',
      'NEXT_PUBLIC_APP_URL="http://localhost:3000"',
    ].join('\n'),
    githubActionsWorkflow: [
      'name: CI',
      'on:',
      '  push:',
      '    branches: [main]',
      '  pull_request:',
      '    branches: [main]',
      '',
      'jobs:',
      '  ci:',
      '    runs-on: ubuntu-latest',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - uses: actions/setup-node@v4',
      '        with:',
      '          node-version: 20',
      '          cache: pnpm',
      '      - run: corepack enable',
      '      - run: pnpm install --frozen-lockfile',
      '      - run: pnpm type-check',
      '      - run: pnpm lint',
      '      - run: pnpm build',
      '      - run: pnpm test',
    ].join('\n'),
  },
  MICROSERVICES_SCALE: {
    id: 'MICROSERVICES_SCALE',
    name: 'Microservices Scale',
    description: 'Next.js frontend + API services + Docker Compose + Postgres',
    repoTemplate: 'mismo-template-microservices',
    stack: ['Next.js', 'Express', 'Docker', 'PostgreSQL', 'Redis'],
    cursorrules: [
      'Never hardcode secrets or API keys',
      'Use environment variables for all configuration',
      'Each service must have its own error handling',
      'Use TypeScript strict mode across all services',
      'Implement health check endpoints for each service',
      'Use structured logging (JSON format)',
      'All inter-service communication must handle timeouts',
      'No console.log in production code',
      'Forbidden: eval(), Function(), innerHTML assignment',
      'Forbidden: SELECT * queries - always specify columns',
      'Forbidden: Storing plaintext passwords',
      'All Docker images must use non-root users',
    ].join('\n'),
    envExample: [
      '# Database',
      'DATABASE_URL="postgresql://user:password@localhost:5432/mydb"',
      '',
      '# Redis',
      'REDIS_URL="redis://localhost:6379"',
      '',
      '# Auth',
      'JWT_SECRET="generate-a-random-secret"',
      'NEXTAUTH_SECRET="generate-a-random-secret"',
      'NEXTAUTH_URL="http://localhost:3000"',
      '',
      '# Services',
      'API_GATEWAY_URL="http://localhost:4000"',
      'USER_SERVICE_URL="http://localhost:4001"',
      'BILLING_SERVICE_URL="http://localhost:4002"',
      '',
      '# App',
      'NEXT_PUBLIC_APP_URL="http://localhost:3000"',
      'NEXT_PUBLIC_API_URL="http://localhost:4000"',
    ].join('\n'),
    githubActionsWorkflow: [
      'name: CI',
      'on:',
      '  push:',
      '    branches: [main]',
      '  pull_request:',
      '    branches: [main]',
      '',
      'jobs:',
      '  ci:',
      '    runs-on: ubuntu-latest',
      '    services:',
      '      postgres:',
      '        image: postgres:16',
      '        env:',
      '          POSTGRES_PASSWORD: postgres',
      '        ports:',
      '          - 5432:5432',
      '        options: >-',
      '          --health-cmd pg_isready',
      '          --health-interval 10s',
      '          --health-timeout 5s',
      '          --health-retries 5',
      '      redis:',
      '        image: redis:7',
      '        ports:',
      '          - 6379:6379',
      '    steps:',
      '      - uses: actions/checkout@v4',
      '      - uses: actions/setup-node@v4',
      '        with:',
      '          node-version: 20',
      '          cache: pnpm',
      '      - run: corepack enable',
      '      - run: pnpm install --frozen-lockfile',
      '      - run: pnpm type-check',
      '      - run: pnpm lint',
      '      - run: pnpm build',
      '      - run: pnpm test',
      '    env:',
      '      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test',
      '      REDIS_URL: redis://localhost:6379',
    ].join('\n'),
  },
}
