import { TEMPLATE_CONFIGS, type TemplateConfig } from './configs'

export interface TemplateFile {
  path: string
  content: string
}

export function generateTemplateFiles(templateId: string): TemplateFile[] {
  const config = TEMPLATE_CONFIGS[templateId]
  if (!config) {
    throw new Error(`Unknown template: ${templateId}`)
  }

  return [
    { path: '.cursorrules', content: generateCursorrules(config) },
    { path: '.env.example', content: config.envExample },
    { path: '.github/workflows/ci.yml', content: config.githubActionsWorkflow },
    { path: 'playwright.config.ts', content: generatePlaywrightConfig(config) },
    { path: 'README.md', content: generateReadme(config) },
  ]
}

function generateCursorrules(config: TemplateConfig): string {
  return [
    `# ${config.name} - Cursor Rules`,
    `# Generated by Mismo Platform`,
    '',
    '## Rules',
    '',
    ...config.cursorrules.split('\n').map((rule) => `- ${rule}`),
    '',
    '## Stack',
    '',
    ...config.stack.map((tech) => `- ${tech}`),
    '',
  ].join('\n')
}

function generatePlaywrightConfig(config: TemplateConfig): string {
  const baseUrl =
    config.id === 'MICROSERVICES_SCALE' ? 'http://localhost:3000' : 'http://localhost:3000'

  return `import { defineConfig, devices } from '@playwright/test'

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: '${baseUrl}',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
  ],
  webServer: {
    command: 'pnpm dev',
    url: '${baseUrl}',
    reuseExistingServer: !process.env.CI,
  },
})
`
}

function generateReadme(config: TemplateConfig): string {
  return `# ${config.name}

${config.description}

## Tech Stack

${config.stack.map((tech) => `- ${tech}`).join('\n')}

## Getting Started

\`\`\`bash
# Install dependencies
pnpm install

# Copy environment variables
cp .env.example .env

# Start development server
pnpm dev
\`\`\`

## Testing

\`\`\`bash
# Run unit tests
pnpm test

# Run E2E tests
pnpm exec playwright test
\`\`\`

---

Generated by [Mismo](https://mismo.dev)
`
}
