export interface DocGeneratorInput {
  projectName: string
  prdJson: {
    archTemplate?: string
    stack?: string[]
    description?: string
    userStories?: Array<{ title: string; description: string }>
    dataBoundaries?: Record<string, string>
    apiSpec?: {
      endpoints?: Array<{
        path: string
        method: string
        description?: string
        requestBody?: unknown
        response?: { status: number; body: unknown }
      }>
    }
    constraints?: {
      concurrentUsers?: number
      maxResponseTimeMs?: number
      uptimeSla?: string
      backupFrequency?: string
    }
  }
  buildMetadata: {
    buildId: string
    studioAssignment?: string
    githubUrl?: string
    vercelUrl?: string
    completedAt: string
  }
  devOpsOutput?: {
    vercelConfig?: unknown
    envTemplate?: string
    deploymentScript?: string
    envRequirements?: Array<{ key: string; required: boolean; description: string }>
  }
}

export interface GeneratedDocuments {
  architectureDecisionRecord: string
  apiContracts: string
  dataBoundaryDocumentation: string
  operationalRunbook: string
  hostingContract: string
}

export interface DocumentFile {
  path: string
  content: string
}

export function generateDeliveryDocuments(input: DocGeneratorInput): GeneratedDocuments {
  return {
    architectureDecisionRecord: generateADR(input),
    apiContracts: generateApiContracts(input),
    dataBoundaryDocumentation: generateDataBoundaryDocs(input),
    operationalRunbook: generateOperationalRunbook(input),
    hostingContract: generateHostingContract(input),
  }
}

export function documentFilesFromGenerated(docs: GeneratedDocuments): DocumentFile[] {
  return [
    { path: 'docs/architecture_decision_record.md', content: docs.architectureDecisionRecord },
    { path: 'docs/api_contracts.json', content: docs.apiContracts },
    { path: 'docs/data_boundary_documentation.md', content: docs.dataBoundaryDocumentation },
    { path: 'docs/operational_runbook.md', content: docs.operationalRunbook },
    { path: 'docs/hosting_contract.json', content: docs.hostingContract },
  ]
}

function generateADR(input: DocGeneratorInput): string {
  const { projectName, prdJson, buildMetadata } = input
  const stack = prdJson.stack ?? []
  const template = prdJson.archTemplate ?? 'Unknown'

  const stackSection = stack.length > 0
    ? stack.map((t) => `- ${t}`).join('\n')
    : '- Not specified'

  return `# Architecture Decision Record

## Project: ${projectName}

**Date:** ${buildMetadata.completedAt}
**Build ID:** ${buildMetadata.buildId}
**Status:** Accepted

---

## Context

${prdJson.description ?? 'No project description provided.'}

The project required a technology stack and architectural pattern that balances development velocity, maintainability, and scalability requirements.

## Decision

### Architecture Pattern: ${template}

This pattern was selected based on the PRD requirements, target user base, and scaling constraints.

### Technology Stack

${stackSection}

### Key Rationale

1. **Framework Choice**: Selected for server-side rendering capabilities, strong TypeScript support, and ecosystem maturity.
2. **Database**: PostgreSQL via Supabase provides RLS, real-time subscriptions, and managed infrastructure.
3. **Deployment**: ${buildMetadata.vercelUrl ? 'Vercel deployment for edge performance and zero-config CI/CD.' : 'Self-hosted deployment configured.'}
4. **Architecture Template**: ${template} was chosen to match the project's complexity and scaling requirements.

## Consequences

### Positive
- Strong type safety across the full stack
- Rapid iteration with hot module reload
- Production-grade auth and database out of the box

### Negative
- Vendor lock-in to the selected hosting platform
- Template constraints limit certain architectural deviations

### Risks
- Third-party service dependencies require monitoring
- Database migration complexity increases with schema changes

---

## Build Provenance

| Field | Value |
|-------|-------|
| Build ID | \`${buildMetadata.buildId}\` |
| Studio | ${buildMetadata.studioAssignment ?? 'N/A'} |
| Repository | ${buildMetadata.githubUrl ?? 'Pending transfer'} |
| Deployment | ${buildMetadata.vercelUrl ?? 'Pending setup'} |
| Completed | ${buildMetadata.completedAt} |

---

*Generated by Mismo Delivery Pipeline*
`
}

function generateApiContracts(input: DocGeneratorInput): string {
  const endpoints = input.prdJson.apiSpec?.endpoints ?? []

  const contracts = {
    version: '1.0.0',
    project: input.projectName,
    generatedAt: input.buildMetadata.completedAt,
    buildId: input.buildMetadata.buildId,
    endpoints: endpoints.map((ep) => ({
      path: ep.path,
      method: ep.method.toUpperCase(),
      description: ep.description ?? '',
      requestBody: ep.requestBody ?? null,
      response: ep.response ?? { status: 200, body: null },
    })),
    metadata: {
      totalEndpoints: endpoints.length,
      authRequired: endpoints.some(
        (ep) => ep.path.includes('/api/') && !ep.path.includes('/public/'),
      ),
    },
  }

  return JSON.stringify(contracts, null, 2)
}

function generateDataBoundaryDocs(input: DocGeneratorInput): string {
  const { projectName, prdJson } = input
  const boundaries = prdJson.dataBoundaries ?? {}
  const boundaryKeys = Object.keys(boundaries)

  const boundarySection = boundaryKeys.length > 0
    ? boundaryKeys.map((key) => `### ${key}\n\n${boundaries[key]}`).join('\n\n')
    : `### Default Boundaries

- **Application Database**: All user data stored in PostgreSQL (Supabase). Row-Level Security enforced.
- **Client-Side Storage**: Session tokens in httpOnly cookies. No PII in localStorage.
- **Third-Party APIs**: External service calls made server-side only. No API keys exposed to client.
- **File Storage**: User uploads stored in Supabase Storage with signed URLs.`

  return `# Data Boundary Documentation

## Project: ${projectName}

This document defines where data resides, how it flows between boundaries, and privacy compliance measures.

---

## Data Residency

${boundarySection}

---

## Data Flow Rules

1. **PII never crosses to client-side storage** — All personally identifiable information is stored server-side in the application database with RLS enabled.
2. **API keys are server-side only** — Third-party credentials are stored as environment variables, never bundled in client code.
3. **Session management** — Authentication tokens use httpOnly, secure, sameSite cookies.
4. **Data export** — User data export follows GDPR Article 20 (data portability) requirements.

## Privacy Compliance

| Requirement | Implementation |
|-------------|---------------|
| Data encryption at rest | Supabase PostgreSQL with AES-256 |
| Data encryption in transit | TLS 1.3 enforced |
| Access control | Row-Level Security policies |
| Audit logging | Database triggers on sensitive tables |
| Data retention | Configurable per data category |

---

*Generated by Mismo Delivery Pipeline*
`
}

function generateOperationalRunbook(input: DocGeneratorInput): string {
  const { projectName, devOpsOutput, buildMetadata } = input
  const envRequirements = devOpsOutput?.envRequirements ?? []

  const envSection = envRequirements.length > 0
    ? envRequirements.map((e) => `| \`${e.key}\` | ${e.required ? 'Yes' : 'No'} | ${e.description} |`).join('\n')
    : '| *No env vars documented* | — | — |'

  const deployScript = devOpsOutput?.deploymentScript
    ? `\`\`\`bash\n${devOpsOutput.deploymentScript}\n\`\`\``
    : '```bash\n# Standard Vercel deployment\nvercel --prod\n```'

  return `# Operational Runbook

## Project: ${projectName}

This document covers deployment, monitoring, troubleshooting, secret rotation, and scaling procedures.

---

## 1. Deployment

### Prerequisites
- Node.js 20+
- pnpm 9+
- Access to hosting platform dashboard

### Deploy to Production

${deployScript}

### Environment Variables

| Variable | Required | Description |
|----------|----------|-------------|
${envSection}

### Post-Deploy Verification
1. Check deployment URL returns 200
2. Verify database connection (health endpoint)
3. Confirm authentication flow works
4. Check third-party integrations respond

---

## 2. Monitoring

### Health Checks
- **Application**: \`GET /api/health\` — should return \`{ status: "ok" }\`
- **Database**: Connection pool metrics via Supabase dashboard
- **Uptime**: Configure external monitor (e.g., BetterStack) on the production URL

### Alerting
- Set up alerts for: 5xx error rate > 1%, response time > 2s, deployment failures

---

## 3. Troubleshooting

### Common Issues

| Symptom | Cause | Fix |
|---------|-------|-----|
| 500 errors on API routes | Missing env vars | Check all required env vars are set |
| Auth redirects failing | Incorrect callback URLs | Update OAuth callback URLs in provider dashboard |
| Database connection refused | Pool exhausted | Restart connection pooler or increase pool size |
| Build failures | Dependency conflict | Clear node_modules and lockfile, reinstall |

### Log Access
- Application logs: Hosting platform dashboard (Vercel / Railway / etc.)
- Database logs: Supabase dashboard > Logs

---

## 4. Secret Rotation

### Rotation Schedule
- **Database passwords**: Every 90 days
- **API keys**: Every 180 days or on suspected compromise
- **JWT secrets**: Every 90 days (requires user re-authentication)

### Rotation Procedure
1. Generate new secret/key in the provider dashboard
2. Update environment variable in hosting platform
3. Redeploy the application
4. Verify functionality with new credentials
5. Revoke old secret/key

---

## 5. Scaling

### Horizontal Scaling
- Serverless functions auto-scale with request volume
- Database: Upgrade Supabase plan for more connections/compute

### Performance Tuning
- Enable caching headers for static assets
- Use ISR (Incremental Static Regeneration) for semi-static pages
- Optimize database queries (add indexes for slow queries)

---

## Build Reference

| Field | Value |
|-------|-------|
| Build ID | \`${buildMetadata.buildId}\` |
| Repository | ${buildMetadata.githubUrl ?? 'Pending transfer'} |
| Deployment | ${buildMetadata.vercelUrl ?? 'Pending setup'} |

---

*Generated by Mismo Delivery Pipeline*
`
}

function generateHostingContract(input: DocGeneratorInput): string {
  const constraints = input.prdJson.constraints ?? {}

  const contract = {
    version: '1.0.0',
    project: input.projectName,
    generatedAt: input.buildMetadata.completedAt,
    buildId: input.buildMetadata.buildId,
    sla: {
      uptimeTarget: constraints.uptimeSla ?? '99.9%',
      maxResponseTimeMs: constraints.maxResponseTimeMs ?? 500,
      concurrentUsersSupported: constraints.concurrentUsers ?? 100,
      supportResponseTimeHours: 24,
    },
    backup: {
      frequency: constraints.backupFrequency ?? 'daily',
      retentionDays: 30,
      pointInTimeRecovery: true,
      backupLocation: 'Same region as primary database',
    },
    monitoring: {
      healthEndpoint: '/api/health',
      metricsAccess: 'Hosting platform dashboard',
      logRetentionDays: 30,
      alertChannels: ['email'],
    },
    scaling: {
      autoScale: true,
      minInstances: 1,
      maxInstances: constraints.concurrentUsers
        ? Math.ceil(constraints.concurrentUsers / 100)
        : 10,
      scalingMetric: 'concurrent_requests',
    },
    environmentVariables: (input.devOpsOutput?.envRequirements ?? []).map((e) => ({
      key: e.key,
      required: e.required,
      description: e.description,
    })),
  }

  return JSON.stringify(contract, null, 2)
}
