[mac_studios]
studio-1 ansible_host=192.168.1.101 ansible_user=admin desired_hostname=studio-1
studio-2 ansible_host=192.168.1.102 ansible_user=admin desired_hostname=studio-2
studio-3 ansible_host=192.168.1.103 ansible_user=admin desired_hostname=studio-3

[mac_studios:vars]
ansible_python_interpreter=/usr/bin/python3
