[mac_studios:children]
control_plane
execution_plane

[control_plane]
studio-1 ansible_host=100.124.80.81 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/mismo_ed25519

[execution_plane]
studio-2 ansible_host=100.76.153.69 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/mismo_ed25519
studio-3 ansible_host=100.84.227.120 ansible_user=admin ansible_ssh_private_key_file=~/.ssh/mismo_ed25519