import express from 'express'
import { prisma } from '@mismo/db'

const app = express()
app.use(express.json({ limit: '10mb' }))

interface HostingConfig {
  provider: 'vercel' | 'aws'
  region: string
  framework: string
  buildCommand: string
  outputDir: string
}

interface EnvRequirement {
  key: string
  required: boolean
  description: string
}

interface GenerateRequest {
  buildId: string
  hostingConfig: HostingConfig
  envRequirements: EnvRequirement[]
}

function generateVercelConfig(config: HostingConfig): Record<string, unknown> {
  const vercelConfig: Record<string, unknown> = {
    version: 2,
    framework: config.framework,
    buildCommand: config.buildCommand,
    outputDirectory: config.outputDir,
    regions: [config.region],
  }

  if (config.framework === 'nextjs') {
    vercelConfig.functions = {
      'api/**': { memory: 1024, maxDuration: 30 },
    }
  }

  vercelConfig.headers = [
    {
      source: '/(.*)',
      headers: [
        { key: 'X-Content-Type-Options', value: 'nosniff' },
        { key: 'X-Frame-Options', value: 'DENY' },
        { key: 'X-XSS-Protection', value: '1; mode=block' },
      ],
    },
  ]

  return vercelConfig
}

function generateEnvTemplate(envRequirements: EnvRequirement[]): string {
  const lines = [
    '# ===========================================',
    '# Environment Variables',
    '# Generated by DevOps Agent',
    '# ===========================================',
    '',
  ]

  const required = envRequirements.filter((e) => e.required)
  const optional = envRequirements.filter((e) => !e.required)

  if (required.length > 0) {
    lines.push('# --- Required ---')
    for (const env of required) {
      lines.push(`# ${env.description}`)
      lines.push(`${env.key}=`)
      lines.push('')
    }
  }

  if (optional.length > 0) {
    lines.push('# --- Optional ---')
    for (const env of optional) {
      lines.push(`# ${env.description}`)
      lines.push(`${env.key}=`)
      lines.push('')
    }
  }

  return lines.join('\n')
}

function generateDeploymentScript(config: HostingConfig, envRequirements: EnvRequirement[]): string {
  const requiredKeys = envRequirements.filter((e) => e.required).map((e) => e.key)

  const envChecks = requiredKeys.map((key) =>
    `  if [ -z "\${${key}}" ]; then\n    echo "ERROR: ${key} is not set"\n    exit 1\n  fi`,
  )

  if (config.provider === 'vercel') {
    return [
      '#!/usr/bin/env bash',
      'set -euo pipefail',
      '',
      'echo "=== Mismo Deployment Script ==="',
      'echo "Provider: Vercel"',
      `echo "Framework: ${config.framework}"`,
      `echo "Region: ${config.region}"`,
      '',
      '# Verify required environment variables',
      'check_env() {',
      ...envChecks,
      '  echo "All required env vars are set."',
      '}',
      '',
      'check_env',
      '',
      '# Install dependencies',
      'echo "Installing dependencies..."',
      'pnpm install --frozen-lockfile',
      '',
      '# Build',
      'echo "Building..."',
      `${config.buildCommand}`,
      '',
      '# Deploy',
      'echo "Deploying to Vercel..."',
      'npx vercel --prod --yes',
      '',
      'echo "Deployment complete."',
      '',
    ].join('\n')
  }

  return [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    'echo "=== Mismo Deployment Script ==="',
    `echo "Provider: ${config.provider}"`,
    `echo "Framework: ${config.framework}"`,
    `echo "Region: ${config.region}"`,
    '',
    '# Verify required environment variables',
    'check_env() {',
    ...envChecks,
    '  echo "All required env vars are set."',
    '}',
    '',
    'check_env',
    '',
    '# Install dependencies',
    'echo "Installing dependencies..."',
    'pnpm install --frozen-lockfile',
    '',
    '# Build',
    'echo "Building..."',
    `${config.buildCommand}`,
    '',
    `echo "Build complete. Output in ${config.outputDir}/"`,
    '',
  ].join('\n')
}

function validateEnvTemplate(template: string, envRequirements: EnvRequirement[]): string[] {
  const errors: string[] = []
  for (const env of envRequirements) {
    if (!template.includes(`${env.key}=`)) {
      errors.push(`Missing env var ${env.key} in template`)
    }
  }
  return errors
}

app.post('/generate', async (req, res) => {
  let buildId: string | undefined

  try {
    const body = req.body as GenerateRequest
    buildId = body.buildId

    if (!buildId || !body.hostingConfig || !body.envRequirements) {
      res.status(400).json({ success: false, error: 'Missing required fields: buildId, hostingConfig, envRequirements' })
      return
    }

    const { hostingConfig, envRequirements } = body

    const vercelConfig = generateVercelConfig(hostingConfig)
    const envTemplate = generateEnvTemplate(envRequirements)
    const deploymentScript = generateDeploymentScript(hostingConfig, envRequirements)

    const validationErrors = validateEnvTemplate(envTemplate, envRequirements)
    if (validationErrors.length > 0) {
      const build = await prisma.build.findUnique({ where: { id: buildId } })
      if (build) {
        const existing = Array.isArray(build.errorLogs) ? build.errorLogs : []
        await prisma.build.update({
          where: { id: buildId },
          data: {
            failureCount: { increment: 1 },
            errorLogs: [...(existing as any[]), { source: 'devops', errors: validationErrors, timestamp: new Date().toISOString() }],
          },
        })
      }

      res.status(400).json({
        success: false,
        error: 'Validation failed',
        details: validationErrors,
      })
      return
    }

    res.json({
      success: true,
      vercelConfig,
      envTemplate,
      deploymentScript,
    })
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error)

    if (buildId) {
      try {
        const build = await prisma.build.findUnique({ where: { id: buildId } })
        if (build) {
          const existing = Array.isArray(build.errorLogs) ? build.errorLogs : []
          await prisma.build.update({
            where: { id: buildId },
            data: {
              status: 'FAILED',
              failureCount: { increment: 1 },
              errorLogs: [...(existing as any[]), { source: 'devops', error: message, timestamp: new Date().toISOString() }],
            },
          })
        }
      } catch {
        console.error('Failed to log error to Build record')
      }
    }

    res.status(400).json({ success: false, error: message })
  }
})

app.get('/health', (_req, res) => {
  res.json({ status: 'ok', service: 'devops-agent' })
})

const PORT = Number(process.env.PORT) || 3004
app.listen(PORT, () => {
  console.log(`DevOps Agent listening on :${PORT}`)
})
