import type { N8nWorkflow, N8nCredential } from './schema'

export type DeploymentMode = 'self-hosted' | 'managed' | 'standalone'

export interface DeploymentConfig {
  mode: DeploymentMode
  workflow: N8nWorkflow
  credentials: N8nCredential[]
  projectName: string
  commissionId?: string
  managedN8nUrl?: string
  managedN8nApiKey?: string
  monitoringWebhook?: string
}

export interface DeploymentResult {
  mode: DeploymentMode
  success: boolean
  artifacts: Record<string, string>
  error?: string
}

export class WorkflowDeployer {
  async deploy(config: DeploymentConfig): Promise<DeploymentResult> {
    switch (config.mode) {
      case 'self-hosted':
        return this.deploySelfHosted(config)
      case 'managed':
        return this.deployManaged(config)
      case 'standalone':
        return this.deployStandalone(config)
      default:
        return {
          mode: config.mode,
          success: false,
          artifacts: {},
          error: `Unknown deployment mode: ${config.mode}`,
        }
    }
  }

  private async deploySelfHosted(
    config: DeploymentConfig,
  ): Promise<DeploymentResult> {
    const workflowJson = JSON.stringify(config.workflow, null, 2)
    const envTemplate = this.generateEnvTemplate(config.credentials)
    const readme = this.generateReadme(config)
    const credentialTemplate = this.generateCredentialTemplate(config.credentials)

    return {
      mode: 'self-hosted',
      success: true,
      artifacts: {
        'workflow.json': workflowJson,
        '.env.example': envTemplate,
        'README.md': readme,
        'credentials-template.json': credentialTemplate,
      },
    }
  }

  private async deployManaged(
    config: DeploymentConfig,
  ): Promise<DeploymentResult> {
    const { managedN8nUrl, managedN8nApiKey } = config

    if (!managedN8nUrl || !managedN8nApiKey) {
      return {
        mode: 'managed',
        success: false,
        artifacts: {},
        error:
          'Managed deployment requires managedN8nUrl and managedN8nApiKey',
      }
    }

    try {
      const workflowPayload = {
        ...config.workflow,
        active: true,
      }

      const response = await fetch(`${managedN8nUrl}/api/v1/workflows`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-N8N-API-KEY': managedN8nApiKey,
        },
        body: JSON.stringify(workflowPayload),
      })

      if (!response.ok) {
        const errorBody = await response.text()
        return {
          mode: 'managed',
          success: false,
          artifacts: {},
          error: `n8n API returned ${response.status}: ${errorBody}`,
        }
      }

      const result = (await response.json()) as { id: string }

      for (const cred of config.credentials) {
        await fetch(`${managedN8nUrl}/api/v1/credentials`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-N8N-API-KEY': managedN8nApiKey,
          },
          body: JSON.stringify({
            name: cred.name,
            type: cred.type,
            data: cred.data || {},
          }),
        })
      }

      const readme = this.generateReadme(config)

      return {
        mode: 'managed',
        success: true,
        artifacts: {
          workflowId: result.id,
          n8nUrl: `${managedN8nUrl}/workflow/${result.id}`,
          'README.md': readme,
        },
      }
    } catch (err) {
      return {
        mode: 'managed',
        success: false,
        artifacts: {},
        error: err instanceof Error ? err.message : 'Failed to deploy to managed n8n',
      }
    }
  }

  private async deployStandalone(
    config: DeploymentConfig,
  ): Promise<DeploymentResult> {
    const workflowJson = JSON.stringify(config.workflow, null, 2)
    const envTemplate = this.generateEnvTemplate(config.credentials)
    const readme = this.generateReadme(config)
    const packageJson = this.generateStandalonePackageJson(config.projectName)
    const entrypoint = this.generateStandaloneEntrypoint()
    const dockerfile = this.generateStandaloneDockerfile()

    return {
      mode: 'standalone',
      success: true,
      artifacts: {
        'workflow.json': workflowJson,
        '.env.example': envTemplate,
        'README.md': readme,
        'package.json': packageJson,
        'index.js': entrypoint,
        Dockerfile: dockerfile,
      },
    }
  }

  private generateEnvTemplate(credentials: N8nCredential[]): string {
    const lines = [
      '# ===========================================',
      '# n8n Workflow Credentials',
      '# Generated by Mismo Pipeline',
      '# NEVER commit this file with real values!',
      '# ===========================================',
      '',
    ]

    const seen = new Set<string>()
    for (const cred of credentials) {
      const key = `${cred.type.toUpperCase()}_API_KEY`
      if (seen.has(key)) continue
      seen.add(key)
      lines.push(`# ${cred.name}`)
      lines.push(`${key}=`)
      lines.push('')
    }

    lines.push('# n8n Configuration')
    lines.push('N8N_ENCRYPTION_KEY=')
    lines.push('N8N_PORT=5678')
    lines.push('')

    return lines.join('\n')
  }

  private generateCredentialTemplate(
    credentials: N8nCredential[],
  ): string {
    const template = credentials.map((c) => ({
      name: c.name,
      type: c.type,
      data: Object.fromEntries(
        Object.keys(c.data || {}).map((k) => [k, `<FILL_IN_${k.toUpperCase()}>`]),
      ),
    }))
    return JSON.stringify(template, null, 2)
  }

  generateReadme(config: DeploymentConfig): string {
    const sections: string[] = []

    sections.push(`# ${config.projectName} — Automation Workflow`)
    sections.push('')
    sections.push(
      `This automation was generated by the Mismo platform for the "${config.projectName}" project.`,
    )
    sections.push('')

    sections.push('## How to Modify This Automation')
    sections.push('')
    sections.push('### Workflow Structure')
    sections.push('')
    sections.push(
      'The workflow is defined in `workflow.json`. Each node represents a step in the automation:',
    )
    sections.push('')
    for (const node of config.workflow.nodes) {
      sections.push(`- **${node.name}** (\`${node.type}\`): ${describeNode(node)}`)
    }
    sections.push('')

    sections.push('### Editing the Workflow')
    sections.push('')
    sections.push('1. **Via n8n UI**: Import `workflow.json` into your n8n instance')
    sections.push(
      '   - Go to **Workflows** > **Import from File** and select `workflow.json`',
    )
    sections.push('2. **Via JSON**: Edit `workflow.json` directly')
    sections.push(
      '   - Nodes are in the `nodes` array; connections are in `connections`',
    )
    sections.push('   - Re-import after editing')
    sections.push('')

    sections.push('### Adding a New Step')
    sections.push('')
    sections.push('1. Open the workflow in n8n')
    sections.push(
      '2. Click the **+** button after the node where you want to insert',
    )
    sections.push('3. Search for the integration you need')
    sections.push('4. Configure the node parameters')
    sections.push('5. Save and test with manual execution before activating')
    sections.push('')

    sections.push('### Credentials Setup')
    sections.push('')
    sections.push(
      'Copy `.env.example` to `.env` and fill in your API keys. Never commit `.env` to Git.',
    )
    sections.push('')
    sections.push(
      '| Service | Credential Type | Required |',
    )
    sections.push('|---------|----------------|----------|')
    for (const cred of config.credentials) {
      sections.push(`| ${cred.name} | \`${cred.type}\` | Yes |`)
    }
    sections.push('')

    if (config.monitoringWebhook) {
      sections.push('### Monitoring')
      sections.push('')
      sections.push(
        'This workflow includes an error handler that sends alerts to:',
      )
      sections.push(`\`${config.monitoringWebhook}\``)
      sections.push('')
      sections.push(
        'If the workflow fails, a POST request with error details is sent automatically.',
      )
      sections.push('')
    }

    sections.push('### Troubleshooting')
    sections.push('')
    sections.push('- **Workflow not triggering**: Check that the workflow is set to Active')
    sections.push(
      '- **Credential errors**: Verify your API keys in n8n credentials settings',
    )
    sections.push(
      '- **Unexpected output**: Use the n8n execution log to inspect each node\'s input/output',
    )
    sections.push(
      '- **Timeouts**: Increase the timeout in the node settings or check the external API',
    )
    sections.push('')

    if (config.mode === 'standalone') {
      sections.push('### Running Standalone')
      sections.push('')
      sections.push('```bash')
      sections.push('npm install')
      sections.push('cp .env.example .env')
      sections.push('# Fill in your credentials in .env')
      sections.push('npm start')
      sections.push('```')
      sections.push('')
      sections.push('Or with Docker:')
      sections.push('')
      sections.push('```bash')
      sections.push('docker build -t automation .')
      sections.push('docker run --env-file .env -p 5678:5678 automation')
      sections.push('```')
      sections.push('')
    }

    return sections.join('\n')
  }

  private generateStandalonePackageJson(projectName: string): string {
    const slug = projectName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')

    return JSON.stringify(
      {
        name: `${slug}-automation`,
        version: '1.0.0',
        description: `Standalone n8n automation for ${projectName}`,
        main: 'index.js',
        scripts: {
          start: 'node index.js',
        },
        dependencies: {
          n8n: '^1.70.0',
          dotenv: '^16.4.0',
        },
      },
      null,
      2,
    )
  }

  private generateStandaloneEntrypoint(): string {
    return [
      "require('dotenv').config();",
      "const { Start } = require('n8n');",
      "const path = require('path');",
      "const fs = require('fs');",
      '',
      'async function main() {',
      "  const workflowPath = path.join(__dirname, 'workflow.json');",
      "  const workflowData = JSON.parse(fs.readFileSync(workflowPath, 'utf-8'));",
      '',
      '  process.env.N8N_PORT = process.env.N8N_PORT || "5678";',
      '  process.env.EXECUTIONS_PROCESS = "main";',
      '',
      '  const app = new Start();',
      '  await app.init();',
      '  await app.run();',
      '',
      `  console.log(\`n8n running on port \${process.env.N8N_PORT}\`);`,
      `  console.log('Workflow loaded:', workflowData.name);`,
      '}',
      '',
      'main().catch((err) => {',
      '  console.error("Failed to start:", err);',
      '  process.exit(1);',
      '});',
      '',
    ].join('\n')
  }

  private generateStandaloneDockerfile(): string {
    return [
      'FROM node:20-slim',
      '',
      'WORKDIR /app',
      '',
      'COPY package.json .',
      'RUN npm install --production',
      '',
      'COPY . .',
      '',
      'EXPOSE 5678',
      '',
      'CMD ["node", "index.js"]',
      '',
    ].join('\n')
  }
}

function describeNode(node: { name: string; type: string }): string {
  const descriptions: Record<string, string> = {
    'n8n-nodes-base.webhook': 'Receives incoming HTTP requests',
    'n8n-nodes-base.scheduleTrigger': 'Triggers on a schedule (cron)',
    'n8n-nodes-base.manualTrigger': 'Triggered manually from the n8n UI',
    'n8n-nodes-base.slack': 'Sends messages or interacts with Slack',
    'n8n-nodes-base.notion': 'Creates or updates Notion pages/databases',
    'n8n-nodes-base.googleSheets': 'Reads or writes Google Sheets data',
    'n8n-nodes-base.emailSend': 'Sends email via SMTP',
    'n8n-nodes-base.httpRequest': 'Makes HTTP requests to external APIs',
    'n8n-nodes-base.errorTrigger': 'Catches workflow execution errors',
    'n8n-nodes-base.set': 'Sets or transforms data fields',
  }
  return descriptions[node.type] || `Custom node (${node.type})`
}
